# -- 코드를 입력하세요
# SELECT *
# FROM PRODUCT P
# JOIN OFFLINE_SALE OS
# WHERE P.PRODUCT_ID = OS.PRODUCT_ID

SELECT P.PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE OS
WHERE P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC