# -- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
JOIN (SELECT MAX(FAVORITES) AS MAX_FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) S
ON R.FAVORITES = S.MAX_FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC
