-- 코드를 작성해주세요
SELECT
    ID,
    CASE
        WHEN RANKED/TOTAL_COUNT <= 0.25 THEN "CRITICAL"
        WHEN RANKED/TOTAL_COUNT <= 0.5 THEN "HIGH"
        WHEN RANKED/TOTAL_COUNT <= 0.75 THEN "MEDIUM"
        ELSE "LOW" END
        AS COLONY_NAME
FROM (SELECT
        *,
        ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKED,
        COUNT(*) OVER() AS TOTAL_COUNT
      FROM
        ECOLI_DATA) T
ORDER BY
    ID ASC