-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH,
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM
    USER_INFO UI
JOIN
    ONLINE_SALE OS
ON
    UI.USER_ID = OS.USER_ID
GROUP BY
    YEAR, MONTH, GENDER
HAVING
    GENDER IS NOT NULL
ORDER BY
    YEAR ASC,
    MONTH ASC,
    GENDER ASC