-- 코드를 작성해주세요
SELECT
    ED2.ID AS ID,
    ED2.GENOTYPE AS GENOTYPE,
    ED1.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA ED1
JOIN
    ECOLI_DATA ED2
ON 
    ED1.ID = ED2.PARENT_ID
WHERE
    ED2.GENOTYPE & ED1.GENOTYPE = ED1.GENOTYPE
ORDER BY
    ED2.ID ASC