-- 코드를 작성해주세요
WITH 
SC AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'
),
SP AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
)

SELECT 
    D.ID, 
    D.EMAIL, 
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS D,
    SC,
    SP
WHERE
    D.SKILL_CODE & SC.CODE = SC.CODE
    OR
    D.SKILL_CODE & SP.CODE = SP.CODE
ORDER BY
    ID ASC