-- 코드를 작성해주세요
WITH T AS (
    SELECT
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
)

SELECT
    T.YEAR,
    T.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA E
JOIN
    T
ON
    EXTRACT(YEAR FROM E.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY
    T.YEAR ASC,
    YEAR_DEV ASC
