WITH T AS (SELECT
    FNI.FISH_NAME,
    FI.FISH_TYPE,
    MAX(FI.LENGTH) AS MAX_LENGTH
FROM
    FISH_INFO FI
JOIN
    FISH_NAME_INFO FNI
ON
    FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY
    FNI.FISH_NAME,
    FI.FISH_TYPE)

SELECT
    FI.ID,
    T.FISH_NAME,
    T.MAX_LENGTH AS LENGTH
FROM 
    FISH_INFO FI,
    T
WHERE
    FI.FISH_TYPE = T.FISH_TYPE
    AND
    FI.LENGTH = T.MAX_LENGTH
ORDER BY
    FI.ID ASC