-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT)
AS "FILE_PATH"
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_FILE UGF
WHERE UGB.VIEWS = (SELECT MAX(VIEWS)
                  FROM USED_GOODS_BOARD)
AND UGB.BOARD_ID = UGF.BOARD_ID
ORDER BY UGF.FILE_ID DESC