-- 코드를 입력하세요
WITH T AS (SELECT
    CATEGORY AS MAX_CATEGORY,
    MAX(PRICE) AS MAX_PRICE
FROM
    FOOD_PRODUCT
WHERE
    CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY
    CATEGORY
)
SELECT
    FP.CATEGORY,
    T.MAX_PRICE,
    FP.PRODUCT_NAME
FROM
    FOOD_PRODUCT FP
JOIN
    T
ON
    FP.CATEGORY = T.MAX_CATEGORY
WHERE
    FP.CATEGORY = T.MAX_CATEGORY
    AND
    FP.PRICE = T.MAX_PRICE
ORDER BY
    FP.PRICE DESC